image: oven/bun:1

stages:
  - build
  - package
  - deploy

build:
  stage: build
  only:
    - docs
  script:
    - echo "Building the app"
    - sh ./docs/build-static-website.sh
    - mkdir -p $CI_PROJECT_DIR/public/
    - cp -r ./docs/dist/* $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - public/
    expire_in: 1 week

package:
  stage: package
  only:
    - docs
  image: debian:bullseye
  before_script:
    - apt-get update && apt-get install -y zip
  script:
  - cd public
  - zip -r ../apex-local-docs.zip ./*
  - cd ..
  - mkdir -p deploy
  - mv apex-local-docs.zip deploy/
  artifacts:
    paths:
      - deploy/apex-local-docs.zip
    expire_in: 1 week
  needs:
    - build

deploy_to_production:
  stage: deploy
  tags:
    - prod_web
  only:
    - docs
  script:
    - echo "Deploying on webserver"
    - unzip -o deploy/apex-local-docs.zip -d /var/www/united-codes/products/uc-local-apex-dev/docs/
    - sudo -n /bin/chown -R gitlab-deploy:gitlab-deploy /var/www/united-codes/products/uc-local-apex-dev/docs/
    - sudo -n /usr/bin/find /var/www/united-codes/products/uc-local-apex-dev/docs/ -type d -exec chmod 755 {} \;
    - sudo -n /usr/bin/find /var/www/united-codes/products/uc-local-apex-dev/docs/ -type f -exec chmod 644 {} \;
  environment:
    name: production_webserver
    url: https://www.united-codes.com/products/uc-local-apex-dev/docs/
  needs:
    - package
