prompt Installing fixture objects

create table t_widgets (
  id   number generated by default as identity primary key,
  name varchar2(100 char) not null
);

create or replace package pkg_widgets as
  function get_count return number;
end pkg_widgets;
/

create or replace package body pkg_widgets as
  function get_count return number is
    l_num number;
  begin
    select count(*) into l_num from t_widgets;
    return l_num;
  end get_count;
end pkg_widgets;
/

insert into t_widgets (name) values ('alpha');
insert into t_widgets (name) values ('beta');
insert into t_widgets (name) values ('gamma');
commit;
